image: python:3.11-slim

stages:
  - deploy

pages:
  stage: deploy
  script:
    - python3 -m pip install sphinx git+https://github.com/bashtage/sphinx-material.git sphinx-tabs myst_parser
    - sphinx-build docs/src/ public/
  artifacts:
    paths:
      - public
  only:
    - main
