services:
  dashlab:
    container_name: dashlab-container
    build:
      context: ".."
      dockerfile: ./docker/dev.Dockerfile
    image: dashlab-dev:latest
    command: python3 -m app.main
    volumes:
      - dashlab_code:/usr/src/app/:rw
    ports:
      - 7777:7777
    networks:
      - mynetwork # Attach to 'mynetwork'
    env_file:
      - "../.env"

  mongo:
    image: mongo:latest # Official MongoDB image
    container_name: mongo_db
    restart: always
    env_file:
      - "../.env"
    ports:
      - "27017:27017" # Expose MongoDB default port
    volumes:
      - mongo_data:/data/db
    networks:
      - mynetwork # Attach to 'mynetwork'

volumes:
  dashlab_code:
    driver: local
    labels:
      project: dashlab
    driver_opts:
      type: none
      o: bind
      device: ../
  mongo_data:
    labels:
      project: dashlab
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../mongo_data

networks:
  mynetwork:
    driver: bridge # Use bridge networking
