services:
  dashlab-prod:
    image: 376129839585.dkr.ecr.eu-west-3.amazonaws.com/dashlab:${IMAGE_TAG}
    env_file: ".env"
    ports:
      - "7777:7777"
    restart: always
    networks:
      - dashnet

  mongo:
    image: mongo:latest # Official MongoDB image
    container_name: mongo_db
    restart: always
    env_file:
      - ".env"
    ports:
      - "27017:27017" # Expose MongoDB default port
    volumes:
      - mongo_data:/data/db
    networks:
      - dashnet
    command: ["mongod", "--quiet"]

  caddy:
    image: caddy:2
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - dashnet

networks:
  dashnet:

volumes:
  caddy_data:
  caddy_config:
  mongo_data:
    labels:
      project: dashlab
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./mongo_data
