services:
  dashapp:
    image: 376129839585.dkr.ecr.eu-west-3.amazonaws.com/fsds-dashboard
    env_file: "../.env"
    ports:
      - "7777:7777"
    restart: always
    networks:
      - dashnet

  caddy:
    image: caddy:2
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - dashnet

networks:
  dashnet:

volumes:
  caddy_data:
  caddy_config:
